In [1]:
import numpy as np
from scipy import io, integrate, linalg, signal
from scipy.sparse.linalg import eigs

In [3]:
for i in range(1, 4):
   print(i)

1
2
3


In [4]:
a = True
b = False

In [5]:
a and b

False

In [7]:
a or b

True

In [8]:
4 == 4

True

In [9]:
4 == 5

False

In [10]:
a = 4
if a == 4:
    print('a = 4')
elif a == 5:
    print('a = 5')

a = 4


In [11]:
1j

1j

In [12]:
np.finfo(float).eps

2.220446049250313e-16

In [13]:
np.spacing(1)

2.220446049250313e-16

In [17]:
a = np.array([[1,2,3], [4,5,6]])

In [18]:
np.ndim(a)

2

In [19]:
a.ndim

2

In [20]:
np.size(a)

6

In [21]:
a.size

6

In [22]:
np.shape(a)

(2, 3)

In [23]:
a.shape

(2, 3)

In [25]:
a.shape[2-1]

3

In [26]:
np.array([[1. ,2. ,3.], [4. ,5. ,6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
a = np.array([[1,1,1], [1,1,1]])
b = np.array([[2,2], [2,2]])
c = np.array([3,3,3])
d = np.array([4,4])
np.block([[a,b], [c,d]])

array([[1, 1, 1, 2, 2],
       [1, 1, 1, 2, 2],
       [3, 3, 3, 4, 4]])

In [31]:
a = np.array([1,2,3,4])
a[-1]

4

In [35]:
a = np.array([[1.,2.,3.,4.,5.],[6.,7.,8.,9.,10.]])
a[1, 4]

10.0

In [36]:
a[1]

array([ 6.,  7.,  8.,  9., 10.])

In [37]:
a[1, :]

array([ 6.,  7.,  8.,  9., 10.])

In [38]:
a[0:5]

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [39]:
a[:5]

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [40]:
a[0:5, :]

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [41]:
a[-5:]

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [42]:
a[0:3, 4:9]

array([[ 5.],
       [10.]])

In [44]:
a[np.ix_([1], [0, 2])]

array([[6., 8.]])

In [46]:
a[:,0:10:2]

array([[ 1.,  3.,  5.],
       [ 6.,  8., 10.]])

In [47]:
a[:,::2]

array([[ 1.,  3.,  5.],
       [ 6.,  8., 10.]])

In [48]:
a[::-1,:]

array([[ 6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [49]:
a[np.r_[:len(a),0]]

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [50]:
a.transpose()

array([[ 1.,  6.],
       [ 2.,  7.],
       [ 3.,  8.],
       [ 4.,  9.],
       [ 5., 10.]])

In [51]:
a.T

array([[ 1.,  6.],
       [ 2.,  7.],
       [ 3.,  8.],
       [ 4.,  9.],
       [ 5., 10.]])

In [52]:
a.conj().transpose()

array([[ 1.,  6.],
       [ 2.,  7.],
       [ 3.,  8.],
       [ 4.,  9.],
       [ 5., 10.]])

In [53]:
a.conj().T

array([[ 1.,  6.],
       [ 2.,  7.],
       [ 3.,  8.],
       [ 4.,  9.],
       [ 5., 10.]])

In [55]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,3],[2,1]])
a @ b

array([[ 8,  5],
       [20, 13]])

In [56]:
a * b

array([[4, 6],
       [6, 4]])

In [57]:
a/b

array([[0.25      , 0.66666667],
       [1.5       , 4.        ]])

In [58]:
a**3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [65]:
(a > 2)

array([[False, False],
       [ True,  True]])

In [66]:
np.nonzero(a > 2)

(array([1, 1], dtype=int64), array([0, 1], dtype=int64))

In [67]:
a[:,np.nonzero(a > 2)[0]]

array([[2, 2],
       [4, 4]])

In [79]:
a[a < 2]=1

In [74]:
a * (a > 2)

array([[0, 0],
       [3, 4]])

In [77]:
a[:] = 3
a

array([[3, 3],
       [3, 3]])

In [80]:
y = a.copy()
y

array([[3, 3],
       [3, 3]])

In [81]:
y = a[1, :].copy()
y

array([3, 3])

In [83]:
y = a.flatten()
y

array([3, 3, 3, 3])

In [84]:
np.arange(1., 11.) 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [85]:
np.r_[1.:11.]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [86]:
np.r_[1:10:10j]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [87]:
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [88]:
np.r_[:10.] 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [89]:
np.r_[:9:10j]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [90]:
np.arange(1.,11.)[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [91]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [93]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [94]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
np.diag(a)

array([3, 3])

In [96]:
np.diag(a, 0)

array([3, 3])

In [102]:
from numpy.random import default_rng
rng = default_rng(42)
rng.random((3,4))

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [103]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [104]:
np.mgrid[0:9.,0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [111]:
np.meshgrid(np.r_[0:9.],np.r_[0:6.])

[array([[0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.]])]

In [109]:
np.ix_(np.r_[0:9.],np.r_[0:6.])

(array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]),
 array([[0., 1., 2., 3., 4., 5.]]))

In [112]:
np.ogrid[0:9.,0:6.] 

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]),
 array([[0., 1., 2., 3., 4., 5.]])]

In [113]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]),
 array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [116]:
np.ix_([1,2,4],[2,4,5])

(array([[1],
        [2],
        [4]]),
 array([[2, 4, 5]]))

In [120]:
a = np.array([[1,2],[3,4]])
np.tile(a, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [123]:
b = np.array([[4,3],[2,1]])
np.concatenate((a,b),1)

array([[1, 2, 4, 3],
       [3, 4, 2, 1]])

In [124]:
np.hstack((a,b)) 

array([[1, 2, 4, 3],
       [3, 4, 2, 1]])

In [125]:
np.column_stack((a,b))

array([[1, 2, 4, 3],
       [3, 4, 2, 1]])

In [126]:
np.c_[a,b]

array([[1, 2, 4, 3],
       [3, 4, 2, 1]])

In [127]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [128]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [129]:
np.r_[a,b]

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [130]:
a.max()

4

In [131]:
np.nanmax(a)

4

In [132]:
a.max(0)

array([3, 4])

In [133]:
a.max(1)

array([2, 4])

In [134]:
np.maximum(a, b)

array([[4, 3],
       [3, 4]])

In [138]:
np.sqrt(a[0] @ a[0])

2.23606797749979

In [139]:
np.linalg.norm(a[0])

2.23606797749979

In [141]:
np.logical_and(a,b)

array([[ True,  True],
       [ True,  True]])

In [142]:
np.logical_or(a,b)

array([[ True,  True],
       [ True,  True]])

In [143]:
a & b

array([[0, 2],
       [2, 0]], dtype=int32)

In [144]:
a | b

array([[5, 3],
       [3, 5]], dtype=int32)

In [145]:
linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [146]:
linalg.pinv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [151]:
linalg.solve(a, b)

array([[-6., -5.],
       [ 5.,  4.]])

In [152]:
linalg.lstsq(a, b) 

(array([[-6., -5.],
        [ 5.,  4.]]),
 array([], dtype=float64),
 2,
 array([5.4649857 , 0.36596619]))

In [157]:
D,V = linalg.eig(a)
D

array([-0.37228132+0.j,  5.37228132+0.j])

In [158]:
V

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [161]:
U, S, Vh = linalg.svd(a)
U

array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]])

In [162]:
S

array([5.4649857 , 0.36596619])

In [163]:
Vh

array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]])

In [165]:
D,V = linalg.eig(a, b)
D

array([-0.99999998+0.j, -1.00000002+0.j])

In [166]:
V

array([[-0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [168]:
D,V = eigs(a, k = 2)
D

array([-0.37228132+0.j,  5.37228132+0.j])

In [169]:
V

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [170]:
Q,R = linalg.qr(a)
Q

array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]])

In [171]:
R

array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]])

In [173]:
P,L,U = linalg.lu(a)
P

array([[0., 1.],
       [1., 0.]])

In [174]:
L

array([[1.        , 0.        ],
       [0.33333333, 1.        ]])

In [175]:
U

array([[3.        , 4.        ],
       [0.        , 0.66666667]])

In [182]:
np.fft.fft(a)

array([[ 3.+0.j, -1.+0.j],
       [ 7.+0.j, -1.+0.j]])

In [183]:
np.fft.ifft(a)

array([[ 1.5+0.j, -0.5+0.j],
       [ 3.5+0.j, -0.5+0.j]])

In [184]:
np.sort(a)

array([[1, 2],
       [3, 4]])

In [186]:
a.sort(axis=0)
a

array([[1, 2],
       [3, 4]])

In [187]:
np.sort(a, axis = 1) 

array([[1, 2],
       [3, 4]])

In [188]:
a.sort(axis = 1)
a

array([[1, 2],
       [3, 4]])

In [190]:
I = np.argsort(a[:, 0])
b = a[I,:]
b

array([[1, 2],
       [3, 4]])

In [193]:
np.unique(a)

array([1, 2, 3, 4])

In [194]:
a.squeeze()

array([[1, 2],
       [3, 4]])